all: safeadd.out safesubtract.out safemultiply.out safedivide.out

safeadd.out: safeadd.c safeint.o
	gcc safeadd.c safeint.o -o safeadd.out

safesubtract.out: safesubtract.c safeint.o
	gcc safesubtract.c safeint.o -o safesubtract.out

safemultiply.out: safemultiply.c safeint.o
	gcc safemultiply.c safeint.o -o safemultiply.out

safedivide.out: safedivide.c safeint.o
	gcc safedivide.c safeint.o -o safedivide.out

safeint.o: safeint.c safeint.h
	gcc -c safeint.c -o safeint.o

clean:
	rm -f *.o *.out *.exe

